server:
    port: 9090
graphhopper:
    cacheFolder: D:/GraphhopperCache/cache
    customCacheFolder:  D:/GraphhopperCache/cache_custom
    enableElevator: true
    demFile: D:/GraphhopperCache/fujian.tif
spring:
    servlet:
      multipart:
        maxFileSize: 100MB
        maxRequestSize: 1000MB