server:
    port: 9090
graphhopper:
    cacheFolder: D:/cache
    enableElevator: true
    demFile: d:/cache/fujian.tif
spring:
    servlet:
      multipart:
        maxFileSize: 100MB
        maxRequestSize: 1000MB