server:
    port: 9090
graphhopper:
    cacheFolder: D:/GraphhopperCache/cache2d
    customCacheFolder:  D:/GraphhopperCache/cache_custom2d
    enableElevator: false
    demFile: D:/GraphhopperCache/fujian.tif
spring:
    servlet:
      multipart:
        maxFileSize: 100MB
        maxRequestSize: 1000MB